# Generated by Django 5.2.5 on 2025-08-06 14:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_category', models.CharField(choices=[('junior', 'Младшая'), ('middle', 'Средняя'), ('senior', 'Старшая'), ('preparatory', 'Подготовительная'), ('kids', 'Детки')], max_length=20, verbose_name='Возрастная категория')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год набора')),
                ('gender', models.CharField(choices=[('M', 'Мальчики'), ('Д', 'Девочки')], max_length=1, verbose_name='Пол группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'unique_together': {('age_category', 'year', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мальчики'), ('Д', 'Девочки')], max_length=1, verbose_name='Пол')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('expulsion_date', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
