# Generated by Django 5.2.5 on 2025-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gender',
            field=models.CharField(choices=[('Мальчики', 'М'), ('Девочки', 'Д')], max_length=10, verbose_name='Пол группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Мальчики', 'М'), ('Девочки', 'Д')], max_length=20, verbose_name='Пол'),
        ),
    ]
