# Generated by Django 5.2.5 on 2025-08-07 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_group_gender_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x600px', null=True, upload_to='groups/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото группы'),
        ),
    ]
