services:
  web:
    image: ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # Монтирование кода
      - static_volume:/app/staticfiles  # Отдельный том для статики
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.9
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"  # Опционально для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Конфиг Nginx
      - static_volume:/app/staticfiles  # Статика Django
    depends_on:
      - web  # Ждём запуска Django
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: