services:
  web:
    build: .
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"  # Для дебага (в продакшне можно убрать)
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/ssl/certs:/etc/ssl/certs:ro  # Монтируем SSL-сертификаты хоста
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust  # Разрешаем подключения без пароля (только для теста)
    command: postgres -c ssl=off
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/kovylek.ru:/etc/letsencrypt/live/kovylek.ru:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - NGINX_HOST=kovylek.ru
      - NGINX_PORT=443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: