# Generated by Django 5.2.5 on 2025-08-06 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_group_gender_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата занятия')),
                ('start_time', models.TimeField(default='18:00', verbose_name='Время начала')),
                ('duration', models.IntegerField(choices=[(60, '1 час'), (90, '1.5 часа'), (120, '2 часа'), (150, '2.5 часа'), (180, '3 часа')], default=90, verbose_name='Длительность')),
                ('notes', models.TextField(blank=True, help_text='План занятия, особенности и т.д.', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Репетиция',
                'verbose_name_plural': 'Репетиции',
                'ordering': ['-date'],
                'unique_together': {('date', 'group', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Присутствовал (быстрая отметка)')),
                ('status', models.CharField(choices=[('present', 'Присутствовал'), ('absent', 'Отсутствовал'), ('late', 'Опоздал'), ('excused', 'По уважительной причине')], default='absent', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('repetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.repetition')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'unique_together': {('repetition', 'student')},
            },
        ),
    ]
