name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Очистка сервера (безопасная)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/app
            # Удаляем только файлы, а не папки (чтобы избежать ошибок)
            find . -maxdepth 1 -type f ! -name '.env' -delete
            # Удаляем только пустые директории (кроме data/)
            find . -mindepth 1 -type d ! -name 'data' -empty -delete
          "

      - name: Копирование файлов
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/app/

      - name: Перезапуск контейнеров
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/app
            docker compose down
            docker compose up -d --build
          "