name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug - List files before deploy
        run: |
          echo "Содержимое локального .github/workflows:"
          ls -la .github/workflows
          echo "Содержимое удалённого ~/app/.github/workflows:"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "ls -la ~/app/.github/workflows || echo 'Папка не существует!'"

      - name: Nuclear deploy
        run: |
          # 1. Удаляем ВСЁ в папке app
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "rm -rf ~/app/*"

          # 2. Копируем ВСЁ из репозитория
          scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/app/

          # 3. Жёсткая пересборка без кэша
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/app
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          "